; ============================================================
; PyPI 数学生态集成验证 — 勘探 + 测试 + 记录
; ============================================================

(display "=== PyPI Math Ecosystem Integration ===\n")

; ==================== 1. numpy ====================
(display "\n--- numpy 2.4.3 ---")
(newline)
(import numpy as np)
(display "linspace: ")
(display (np.linspace 0 1 5))
(newline)
(display "linalg.solve: ")
(display (np.linalg.solve '#(#(3 1) #(1 2)) '#(9 8)))
(newline)
(display "random.rand: ")
(display (np.random.rand 2 3))
(newline)
(display "fft.fft: ")
(display (np.fft.fft '#(1 0 1 0)))
(newline)

; ==================== 2. scipy ====================
(display "--- scipy 1.17.1 ---")
(newline)
(import scipy)
(import scipy.optimize scipy.stats scipy.signal scipy.interpolate)
(display "minimize: ")
(display (scipy.optimize.minimize (lambda (x) (expt (- x 2) 2)) 0))
(newline)
(display "norm.ppf: ")
(display (scipy.stats.norm.ppf 0.975))
(newline)
(display "butter: ")
(display (scipy.signal.butter 4 0.2))
(newline)
(display "interp1d: ")
(define ff (scipy.interpolate.interp1d '#(0 1 2) '#(0 1 4) :kind 'quadratic))
(display (py-str (ff 1.5)))
(newline)

; ==================== 3. sympy ====================
(display "\n--- sympy 1.14.0 ---")
(newline)
(import sympy)
(defsym x y)
(display "integrate: ")
(display (integrate (sin x) x))
(newline)
(display "dsolve: ")
(define yf (sympy.Function 'y))
(display (dsolve (+ (diff (yf x) x) (yf x)) (yf x) x))
(newline)

; ==================== 4. mpmath ====================
(display "\n--- mpmath 1.3.0 ---")
(newline)
(import mpmath)
(set! mpmath.mp.dps 80)
(display "pi (80 digits): ")
(display mpmath.pi)
(newline)
(display "zeta(2): ")
(display (mpmath.zeta 2))
(newline)

; ==================== 5. statsmodels ====================
(display "\n--- statsmodels 0.14.6 ---")
(newline)
(import statsmodels.api as sm)
(define X (sm.add_constant '#(1 2 3 4 5 6 7 8 9 10)))
(define y '#(2 4 5 4 5 6 8 9 10 12))
(define model (sm.OLS y X))
(define r (model.fit))
(display "OLS params: ")
(display r.params)
(newline)
(display "R-squared: ")
(display r.rsquared)
(newline)

; ==================== 6. pandas ====================
(display "\n--- pandas 3.0.3 ---")
(newline)
(import pandas)
(display "Series: ")
(display (pandas.Series '#(10 20 30) :name 'scores))
(newline)
(define df (pandas.DataFrame (list (list 'Alice 25) (list 'Bob 30)) :columns '#(name age)))
(display "DataFrame: ")
(display df)
(newline)

; ==================== 7. networkx ====================
(display "\n--- networkx (图论) ---")
(newline)
(import networkx)
(define G (networkx.Graph))
(G.add_edge 'A 'B)
(G.add_edge 'B 'C)
(G.add_edge 'C 'A)
(G.add_edge 'C 'D)
(display "shortest_path A->D: ")
(display (networkx.shortest_path G 'A 'D))
(newline)
(display "pagerank: ")
(display (networkx.pagerank G))
(newline)
(display "clustering: ")
(display (networkx.clustering G))
(newline)

; ==================== 8. uncertainties ====================
(display "\n--- uncertainties (误差传播) ---")
(newline)
(import uncertainties)
(import uncertainties.umath)
(define u (uncertainties.ufloat 10.0 0.5))
(define v (uncertainties.ufloat 3.0 0.1))
(display "u: ")
(display u)
(newline)
(display "u + v: ")
(display (+ u v))
(newline)
(display "sin(u): ")
(display (uncertainties.umath.sin u))
(newline)

; ==================== 9. pint ====================
(display "\n--- pint (物理单位) ---")
(newline)
(import pint)
(define ureg (pint.UnitRegistry))
(define dist (ureg.Quantity 5.0 'meter))
(define t (ureg.Quantity 2.0 'second))
(display "distance: ")
(display dist)
(newline)
(display "speed: ")
(display (/ dist t))
(newline)
(display "to km: ")
(display (dist.to 'kilometer))
(newline)

; ==================== 10. symengine ====================
(display "\n--- symengine (高速符号引擎) ---")
(newline)
(import symengine)
(defsym a b)
(display "symengine.expand: ")
(display (symengine.expand (expt (+ a b) 4)))
(newline)
(display "symengine.sin: ")
(display (symengine.sin a))
(newline)

; ==================== 11. galois ====================
(display "\n--- galois (有限域) ---")
(newline)
(import galois)
(define GF (galois.GF 2 8))
(display "GF(2^8): ")
(display GF)
(newline)
(display "GF.primitive_element: ")
(display GF.primitive_element)
(newline)

; ==================== 12. results ====================
(display "\n=== PyPI Math Ecosystem Integration Complete ===")
(newline)

; --- OpenCV ---
(display "\n--- opencv-python 4.13.0 ---")
(newline)
(import cv2)
(import numpy as np)
(define cv2_img (np.zeros '(50 50 3) :dtype np.uint8))
(cv2.rectangle cv2_img '(10 10) '(40 40) '(0 255 0) 1)
(cv2.imwrite "/tmp/cv2_check.png" cv2_img)
(define cv2_check (cv2.imread "/tmp/cv2_check.png"))
(display "imread shape: ")
(display (np.shape cv2_check))
(newline)
(display "cv2: ✅")
(newline)

(display "=== Ecosystem Survey Complete ===")
(newline)